version: '3.9'

services:
  dirac-tuto:
    image: ghcr.io/xenon-middleware/dirac:8.0.39
    privileged: true
    hostname: dirac-tuto
  test:
    build:
      context: ..
      dockerfile: ./tests_dirac/Dockerfile
    volumes:
    - ..:/workspace:cached
    depends_on:
    - dirac-tuto
    # Need to use double quotes as entrypoint is bash -c, which requires single string
    command: "'pip install -e . && pytest -p no:cacheprovider -vv tests_dirac'"
