job_root_dir: /tmp/jobs
destination_picker: bartender.picker:pick_first
applications:
  wc:
    command: wc $config
    config: README.md
destinations:
  local:
    scheduler:
      type: memory
      slots: 1
    filesystem:
      type: local
