# By default the files of jobs are stored in /tmp/jobs
# job_root_dir: /tmp/jobs
# By default jobs are submitted to the first destination
# destination_picker: bartender.config:pick_first
# To use a custom picker set `destination_picker` to a `<module>:<function>`
# The picker should have type bartender.config.DestinationPicker .
applications:
  # The label of the application
  wc:
    # Command line interface command to run application.
    # `$config` occurences will be replaced value of config parameter.
    command: wc $config
    # Name of config file that the application needs
    config: README.md
destinations:
  local:
    scheduler:
      type: memory
      slots: 1
    filesystem:
      type: local
    ## Example of running jobs by current user on snellius.
    # remote:
    #   scheduler:
    #     type: slurm
    #     partition: thin
    #     ssh_config:
    #       hostname: snellius.surf.nl
    #   filesystem:
    #     type: sftp
    #     ssh_config:
    #       hostname: snellius.surf.nl
    #     entry: /scratch-shared/bartender/jobs
    ## Example of running jobs on a slurm Docker container.
    ## Start a container with `docker run --detach --publish 10022:22 xenonmiddleware/slurm:20`
    # slurmcontainer:
    #   scheduler:
    #       type: slurm
    #       partition: mypartition
    #       ssh_config:
    #           port: 10022
    #           hostname: localhost
    #           username: xenon
    #           password: javagat
    #   filesystem:
    #       type: sftp
    #       ssh_config:
    #           port: 10022
    #           hostname: localhost
    #           username: xenon
    #           password: javagat
    #       entry: /home/xenon
