job_root_dir: /tmp/jobs
destination_picker: bartender.picker:pick_first
applications:
  wc:
    command: wc $config
    config: README.md
destinations:
  local:
    scheduler:
      type: memory
      slots: 1
    filesystem:
      type: local
  slurmcontainer:
    scheduler:
      type: slurm
      partition: mypartition
      ssh_config:
        port: 10022
        hostname: localhost
        username: xenon
        password: javagat
    filesystem:
      type: sftp
      ssh_config:
        port: 10022
        hostname: localhost
        username: xenon
        password: javagat
      entry: /home/xenon
