destination_picker: bartender.config:pick_first
applications:
  haddock3:
    command: haddock3 $config
    config: workflow.cfg
  # Below are other haddock3 commands,
  # that could be hosted by bartender web service.
  # TODO add support for label and parameters keys
  # haddock3-pp:
  #   label: HADDOCK3 preprocess PDB files
  #   command: haddock3-pp --output-directory . *.pdb
  # haddock3-analyse:
  #   command: haddock3-analyse --run-dir . --modules $modules
  #   parameters:
  #     modules:
  #       type: array
  #       items:
  #         type: int
  # haddock3-score:
  #   command: haddock3-score --outputpdb --outputpsf $config
  #   config: complex.pdb
destinations:
  local:
    scheduler:
      type: memory
      slots: 1
    filesystem:
      type: local
interactive_applications:
  rescore:
    command: >
      haddock3-re score \
        --w_elec $w_elec --w_vdw $w_vdw --w_desolv $w_desolv --w_bsa $w_bsa --w_air $w_air \
        $capri_dir
    description: Rescore a HADDOCK run with different weights.
    input:
      $schema: https://json-schema.org/draft/2020-12/schema
      additionalProperties: false
      properties:
        capri_dir:
          type: string
        w_air:
          type: number
        w_bsa:
          type: number
        w_desolv:
          type: number
        w_elec:
          type: number
        w_vdw:
          type: number
      required:
      - capri_dir
      - w_elec
      - w_vdw
      - w_desolv
      - w_bsa
      - w_air
      type: object
  reclustrmsd:
    command: >
      haddock3-re clustrmsd
      --criterion $criterion
      --n_clusters $n_clusters --clust_cutoff $clust_cutoff --min_population $min_population
      $clustrmsd_dir
    description: Recluster a HADDOCK run with RSMD and different parameters.
    input:
      $schema: https://json-schema.org/draft/2020-12/schema
      additionalProperties: false
      properties:
        clustrmsd_dir:
          type: string
        criterion:
          type: string
        clust_cutoff:
          type: number
        n_clusters:
          type: number
        min_population:
          type: number
      required:
      - clustrmsd_dir
      - criterion
      - clust_cutoff
      - n_clusters
      - min_population
      type: object
  reclustfcc:
    command: >
      haddock3-re clustfcc
      --clust_cutoff $clust_cutoff --strictness $strictness --min_population $min_population
      $clustfcc_dir
    description: Recluster a HADDOCK run with FCC and different parameters.
    input:
      $schema: https://json-schema.org/draft/2020-12/schema
      additionalProperties: false
      properties:
        clustfcc_dir:
          type: string
        clust_cutoff:
          type: number
        strictness:
          type: number
        min_population:
          type: number
      required:
      - clustfcc_dir
      - clust_cutoff
      - strictness
      - min_population
      type: object
