"""empty message

Revision ID: 300833a7a4c8
Revises: 58af0f14c426
Create Date: 2022-08-30 15:39:50.044644

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "300833a7a4c8"
down_revision = "58af0f14c426"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
