"""empty message

Revision ID: ef872771a841
Revises: 300833a7a4c8
Create Date: 2022-08-30 17:20:20.980685

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ef872771a841"
down_revision = "300833a7a4c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
