"""empty message

Revision ID: 58af0f14c426
Revises:
Create Date: 2022-08-26 13:06:41.550353

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58af0f14c426"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job")
    # ### end Alembic commands ###
