"""user.roles

Revision ID: 3226c12cc7f8
Revises: 024e0181541b
Create Date: 2023-03-02 08:12:57.458098

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3226c12cc7f8"
down_revision = "024e0181541b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "roles",
            postgresql.ARRAY(sa.String(length=24), as_tuple=True, dimensions=1),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "roles")
    # ### end Alembic commands ###
