"""nullablility from optional type

Revision ID: cf2424f395bc
Revises: 3226c12cc7f8
Create Date: 2023-04-03 16:51:29.805598

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf2424f395bc"
down_revision = "3226c12cc7f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "name", existing_type=sa.VARCHAR(length=200), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("job", "name", existing_type=sa.VARCHAR(length=200), nullable=True)
    # ### end Alembic commands ###
