version: '3.9'

services:
  dirac-tuto:
    image: ghcr.io/xenon-middleware/dirac:8.0.18
    privileged: true
    hostname: dirac-tuto
  test:
    build:
      context: ..
      dockerfile: ./tests-dirac/Dockerfile
    volumes:
    - ..:/workspace:cached
    depends_on:
    - dirac-tuto
    # Need to use double quotes as entrypoint is bash -c, which requires single string
    command: "'while sleep 1000; do :; done'"
