version: '3.9'

services:
  dirac-tuto:
    image: ghcr.io/xenon-middleware/dirac:8.0.18
    privileged: true
    hostname: dirac-tuto
  test:
    build:
      context: ..
      dockerfile: ./tests-dirac/Dockerfile
    volumes:
    - ..:/src
    depends_on:
    - dirac-tuto
