"""job.application column added

Revision ID: a31176b2cffa
Revises: ef872771a841
Create Date: 2022-09-09 14:54:25.919290

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a31176b2cffa"
down_revision = "ef872771a841"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("application", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "application")
    # ### end Alembic commands ###
