"""Track job id of internal scheduler

Revision ID: 024e0181541b
Revises: a31176b2cffa
Create Date: 2022-11-10 15:25:04.481346

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "024e0181541b"
down_revision = "a31176b2cffa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("internal_id", sa.String(length=200), nullable=True))
    op.add_column("job", sa.Column("destination", sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "internal_id")
    # ### end Alembic commands ###
