"""job state

Revision ID: 120c85af49ea
Revises: a31176b2cffa
Create Date: 2022-10-21 13:08:14.617880

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "120c85af49ea"
down_revision = "a31176b2cffa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job", sa.Column("state", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job", "state")
    # ### end Alembic commands ###
