name: Dirac tests

on:
  push:
    # Run tests only if dirac code is changed or workflow is triggerd manually
    paths:
    - '**dirac**'
  workflow_dispatch:

jobs:
  dirac_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Pull images
      run: docker compose -f tests_dirac/docker-compose.yml pull
    - name: Build images
      run: docker compose -f tests_dirac/docker-compose.yml build
    - name: Run dirac tests
      timeout-minutes: 15
      run: docker compose -f tests_dirac/docker-compose.yml run test
