name: Testing bartender

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install deps
      run: |
        pip install -U pip wheel
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        # Workaround for random install failures
        POETRY_INSTALLER_PARALLEL: false
    - name: Run black check
      run: poetry run black --check .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install deps
      run: |
        pip install -U pip wheel
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        # Workaround for random install failures
        POETRY_INSTALLER_PARALLEL: false
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install deps
      run: |
        pip install -U pip wheel
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        # Workaround for random install failures
        POETRY_INSTALLER_PARALLEL: false
    - name: Run mypy check
      run: poetry run mypy .
  pytest:
    runs-on: ubuntu-latest
    services:

      bartender-db:
        image: postgres:15.2-bullseye
        env:
          POSTGRES_PASSWORD: bartender
          POSTGRES_USER: bartender
          POSTGRES_DB: bartender
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install deps
      run: |
        pip install -U pip wheel
        pip install poetry
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
        # Workaround for random install failures
        POETRY_INSTALLER_PARALLEL: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="src" .
      env:
        BARTENDER_HOST: "0.0.0.0"
        BARTENDER_DB_HOST: localhost
